id: I5EC22A8B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T09:51:11+00:00'
last_modified: '2022-06-08T01:09:41.059409+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14649
  title: སྲོང་བཙན་ཚངས་དབྱངས། ༼དུས་དེབ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    B4CD:
      image_group_id: I1KG15715
      title: ''
      total_pages: 41
      order: 1
      base_file: B4CD.txt
    5AE7:
      image_group_id: I1KG15716
      title: ''
      total_pages: 60
      order: 2
      base_file: 5AE7.txt
    F955:
      image_group_id: I1KG15717
      title: ''
      total_pages: 58
      order: 3
      base_file: F955.txt
    05AD:
      image_group_id: I1KG15718
      title: ''
      total_pages: 64
      order: 4
      base_file: 05AD.txt
    A6A7:
      image_group_id: I1KG15719
      title: ''
      total_pages: 64
      order: 5
      base_file: A6A7.txt
    2CFA:
      image_group_id: I1KG15720
      title: ''
      total_pages: 70
      order: 6
      base_file: 2CFA.txt
    FAD2:
      image_group_id: I1KG15721
      title: ''
      total_pages: 56
      order: 7
      base_file: FAD2.txt
    B963:
      image_group_id: I1KG15722
      title: ''
      total_pages: 64
      order: 8
      base_file: B963.txt
    1EBC:
      image_group_id: I1KG15723
      title: ''
      total_pages: 60
      order: 9
      base_file: 1EBC.txt
    CDC5:
      image_group_id: I1KG15724
      title: ''
      total_pages: 54
      order: 10
      base_file: CDC5.txt
    92E7:
      image_group_id: I1KG15725
      title: ''
      total_pages: 56
      order: 11
      base_file: 92E7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
